import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { RefreshCw, Image as ImageIcon } from 'lucide-react';

export default function GanImages() {
  const [urls, setUrls] = useState([]);
  const [loading, setLoading] = useState(true);

  const API_BASE = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000';

  useEffect(() => {
    axios.get(`${API_BASE}/generated-images/`)
      .then(res => {
        setUrls(res.data.urls || []);
      })
      .catch(err => console.error("Failed to fetch GAN images"))
      .finally(() => setLoading(false));
  }, [API_BASE]);
  
  return (
    <div className="space-y-8 animate-page-in">
      <div>
        <h2 className="text-3xl font-semibold text-app-text mb-2">
          GAN Image Synthesis
        </h2>
        <p className="text-app-textSecondary">Synthetic training images generated by the adversarial network.</p>
      </div>

      {loading ? (
         <div className="flex justify-center items-center h-64 bg-white border border-app-border rounded-2xl shadow-sm">
           <RefreshCw className="w-8 h-8 animate-spin text-app-textSecondary" />
         </div>
      ) : urls.length > 0 ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
          {urls.map((url, idx) => (
            <div key={idx} className="bg-white border border-app-border rounded-xl overflow-hidden group hover:border-blue-400 hover:shadow-lg transition-all duration-300 shadow-sm">
               <div className="px-4 py-3 border-b border-app-border bg-slate-50 flex justify-between items-center group-hover:bg-app-primaryLight transition-colors">
                 <span className="font-medium text-app-text text-sm">
                    {url.includes('epoch_') ? `Epoch ${url.split('epoch_')[1].split('.')[0]}` : `Image ${idx + 1}`}
                 </span>
                 <span className="w-2 h-2 rounded-full bg-app-primary opacity-0 group-hover:opacity-100 transition-opacity" />
               </div>
               <div className="aspect-square bg-slate-50 flex items-center justify-center relative overflow-hidden">
                  <img 
                    src={`${API_BASE}${url}`}
                    alt={`GAN Output ${idx}`}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    onError={(e) => {
                      e.target.onerror = null; 
                      e.target.style.display = 'none';
                    }}
                  />
               </div>
            </div>
          ))}
        </div>
      ) : (
         <div className="bg-white border border-dashed border-slate-300 rounded-2xl p-16 text-center flex flex-col items-center shadow-sm">
           <ImageIcon className="w-12 h-12 mb-4 text-slate-300" />
           <span className="font-medium text-xl text-app-text mb-2">No Synthetic Imagery Found</span>
           <p className="text-app-textSecondary">Awaiting adversarial training output from the generator module.</p>
         </div>
      )}
    </div>
  );
}
